### ISSUE TITLE
error when assemble chasm

### ISSUE THREAD

**Issue by Innursery** [minad/chasm#1]
I got got this error when I try assemble chasm:

Exception in thread "main" chasm.SExpParser$SExpException: Expected SYM, but got INT:-17 at line 79
	at chasm.SExpParser.err(SExpParser.java:275)
	at chasm.SExpParser.err(SExpParser.java:271)
	at chasm.SExpParser.expect(SExpParser.java:157)
	at chasm.SExpParser.sym(SExpParser.java:56)
	at chasm.ClassParser.parseCodeInsn(ClassParser.java:418)
	at chasm.ClassParser.parseCode(ClassParser.java:286)
	at chasm.ClassParser.parseMethod(ClassParser.java:229)
	at chasm.ClassParser.read(ClassParser.java:86)
	at chasm.Pipeline.run(Pipeline.java:55)
	at chasm.Pipeline.process(Pipeline.java:47)
	at chasm.Main.run(Main.java:38)
	at chasm.Server.main(Server.java:37)
	at chasm.Main.main(Main.java:13)

Any idea ?

**Comment by minad** [comment]
Can you post the chasm code?

**Comment by Innursery** [comment]
send to your email

**Comment by minad** [comment]
Hmm, it seems the chasm file is somehow invalid. Did you generate it from an obfuscated java class file? The symbols look like "-17uxyz".
